### ISSUE TITLE
Items to address before publishing in Steampipe Hub

### ISSUE THREAD

**Issue by johnsmyth** [theapsgroup/steampipe-plugin-gitlab#2]
1. Please add the goreleaser.yaml.  You can copy the [one from steampipe-plugin-vault, but edit id the line to say `id: "steampipe-gitlab"` ](https://github.com/theapsgroup/steampipe-plugin-vault/blob/main/.goreleaser.yml#L22)
2. Please make sure you test against the cloud version of gitlab as well as your local version.  The plugin should work with both, but the cloud version will reveal some multi-tenant considerations that you must address.  
3. For instance, many APIs return ALL items by default.  While this may be sufficient in a private instance, the scale of the shared cloud version will make paging through all the results unfeasible in any practical way. For example, `select * from gitlab_project` returns ALL the public projects, in addition to your own private projects.  We have addressed this in the [github plugin](https://github.com/turbot/steampipe-plugin-github) with the `my` pattern - you will see that we have split some apis into  2 tables, one which requires a qualifier but will return ANY items, and one that does not that only returns "your" resources.  As an example, the `github_repository` table can return information about ANY public repo, but you must specify `where full_name=`, whereas the the `github_my_repository`  does NOT require a qualifier, but only returns repos that you own or contribute to.  Please try to use this pattern as well - let me know if you have questions.
3. Paging seems to be broken, at least against the cloud version.  I did not test all tables, but `select * from gitlab_project` and `select * from gitlab_user` both return only the first 30 items.

**Comment by graza-io** [comment]
Hi John,

I've added a `goreleaser.yml` file as requested.

I have looked into the paging issue with the cloud version (gitlab.com) this was due to the way it doesn't calculate total pages and thus omits this header in the response, have adjusted all usages to work with the next page value instead.

I have provided `my` tables for `issues` and `projects` since these two are the ones that will cause issues when searching without qualifiers on cloud. (group, snippets, etc default to be only those associated with the user). 

However as a caveat to this I haven't required any qualifiers on the `gitlab_issue` / `gitlab_project` / `gitlab_user` tables, since our use-case requires being able to search across everything within our private instance - I did add comments to the documentation about not recommended to use these tables without qualifiers due to performance reasons.
